px-5 set up project
PuppetLogic/PuppetX pull request #6
Opened 2024-05-12 14:28 UTC by Jmendes42

2024-05-15 08:13 UTC, isousa42 requested changes

2024-05-15 08:13 UTC, isousa42 commented on CMakeLists.txt
> +        .
Why do we need to specify the root directory ? I think the sources should be inside other directories, not the root one

2024-05-15 09:47 UTC, Jmendes42 commented on tests/CMakeLists.txt
> +target_link_libraries(${EXECUTABLE_NAME}
Separate with an empty line

2024-05-15 09:48 UTC, jmend3s commented on CMakeLists.txt
> +        .
Nice catch

2024-05-18 21:04 UTC, RealMadnessWorld approved these changes

2024-05-29 21:36 UTC, closed without merging